### PR TITLE
Update pyproject file to be poetry 1.2 compliant.

### PR DESCRIPTION
**Pull request by MylesBartlett**
Make extra dependencies opt-out instead of opt-in.

### CODE REVIEW

**Comment by thomkeh** [comment]
You can also mark an entire group as optional.

**Comment by thomkeh** [comment]
The CI still runs on Python 3.7?

**Comment by MylesBartlett** [comment]
> You can also mark an entire group as optional.

Right but with the ability to now exclude groups and install only the main dependencies I don't think there's much reason to maintain the opt-in scheme we had before.

**Comment by thomkeh** [comment]
Hehe, the test fails because it's been written such that it should fail on pre-3.9 python. Either use 3.8 for the CI or remove the test.

**Comment by MylesBartlett** [comment]
> Hehe, the test fails because it's been written such that it should fail on pre-3.9 python. Either use 3.8 for the CI or remove the test.

Equally, we could just remove the decorator and the associated test given that it no longer sees any use

**Comment by thomkeh** [comment]
Sure, I've never used it.

**Pull request merged**
