### PR TITLE
partial

### PR DESCRIPTION
**Pull request by MylesBartlett**
- Improve yaml formatting.
- Add properly-typed re-implementation of partial.
- Rename func to cbl.

### CODE REVIEW

**Comment by thomkeh** [comment]
Partial from the std library is not typed? :shocked_face:

**Comment by MylesBartlett** [comment]
> Partial from the std library is not typed? :shocked_face:

I thought it was just the use of generics that was missing but, indeed quite shockingly,there appear to be no annotations whatsoever. Anyway while a major improvement, this implementation can't propagate generic return types (though, at the same time, I'm not sure this is something that can even be solved).

**Comment by thomkeh** [comment]
This is how it's typed in the stdlib:

```python
 ​class​ ​partial​(​Generic​[​_T​]): 
 ​    ​@​property 
 ​    ​def​ ​func​(​self​) ​->​ ​Callable​[..., ​_T​]: ... 
 ​    ​@​property 
 ​    ​def​ ​args​(​self​) ​->​ ​tuple​[​Any​, ...]: ... 
 ​    ​@​property 
 ​    ​def​ ​keywords​(​self​) ​->​ ​dict​[​str​, ​Any​]: ... 
 ​    ​def​ ​__new__​(​cls​: ​type​[​Self​], ​__func​: ​Callable​[..., ​_T​], ​*​args​: ​Any​, ​**​kwargs​: ​Any​) ​->​ ​Self​: ... 
 ​    ​def​ ​__call__​(​__self​, ​*​args​: ​Any​, ​**​kwargs​: ​Any​) ​->​ ​_T​: ... 
 ​    ​if​ ​sys​.​version_info​ ​>=​ (​3​, ​9​): 
 ​        ​def​ ​__class_getitem__​(​cls​, ​item​: ​Any​) ​->​ ​GenericAlias​: ...
```

**Comment by MylesBartlett** [comment]
Oh, of course the annotations wouldn't be included along with the implementation but in a separate type-stubs file.

**Comment by MylesBartlett** [comment]
Never mind then; something else must have interfered with the annotation-propagation and after checking the implementation of partial I assumed this was to blame.

**Pull request closed without merging**
